# checkpoint-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoint-pvc
  namespace: sumin
spec:
  accessModes:
    - ReadWriteMany
  volumeName: checkpoint-pv
  resources:
    requests:
      storage: 1Gi

