apiVersion: ai.mljob-controller/v1
kind: MLJob
metadata:
  name: mljob-train-sumin
  namespace: sumin
spec:
  image: itoodo12/train:v5
  cpu: "5"
  checkpointPVC: checkpoint-pvc
  checkpointPath: /mnt/data/checkpoints
  queueName: training-queue

