apiVersion: apps/v1
kind: Deployment
metadata:
  name: mljob-controller
  namespace: sumin
spec:
  replicas: 1
  selector:                         
    matchLabels:
      app: mljob-controller
  template:
    metadata:
      labels:
        app: mljob-controller       
    spec:
      serviceAccountName: mljob-controller-sa
      containers:
        - name: controller
          image: itoodo12/mljob-controller:latest
          volumeMounts:
            - mountPath: /mnt/data/checkpoints
              name: checkpoint-volume
      volumes:
        - name: checkpoint-volume
          persistentVolumeClaim:
            claimName: checkpoint-pvc

